### ISSUE TITLE
Question: How do references to other components' output work?

### ISSUE THREAD

**Issue by jedfoster** [serverless-components/fullstack-app#16]
This is a more general question about working with Serverless Components, not necessarily specific to this repo. If there's a better place to post this, let me know.

The API component in this repo references output from the permissions and database components. _How_ does that work?

See [api/serverless.yml lines 9](https://github.com/serverless-components/fullstack-app/blob/master/api/serverless.yml#L9), [17](https://github.com/serverless-components/fullstack-app/blob/master/api/serverless.yml#L17), and [19](https://github.com/serverless-components/fullstack-app/blob/master/api/serverless.yml#L17):

```yaml
component: express
app: fullstack
name: api

inputs:
  # Express application source code.
  src: ./
  # Permissions required for the AWS Lambda function to interact with other resources
  roleName: ${output:permissions.name}  # <<--- _HOW_ does this work??
```

AFAICT, the only linkages between the API component and the permissions component are the `app` values, and directory structure (`api/` and `permissions/` being siblings).

I'm trying to add a layer to a lambda using those conventions—sibling directories, same `app` values—but I keep getting `invalid reference ${output:commoncode.arnVersion}`. What am I missing? How do these output references work?
