### ISSUE TITLE
setting a custom domain doesn't do anything

### ISSUE THREAD

**Issue by franciskolms** [serverless-components/fullstack-app#21]
According to the documentation, all I need to do is write `domain: example.com` in the serverless.yml to get the https://xxxxxx.cloudfront.net automatically route to my domain. So that's exactly what I did, I went to fullstack-app > site > serverless.yml and added the domain name where it was supposed to go like so:

```
component: website
name: site

inputs:
  src:
    src: ./
    hook: npm run build
    dist: build
    domain: example.com
```

Simple I thought.

However, when I deploy the app nothing happens with the domain and the site is only accessible through the usual https://xxxxxx.cloudfront.net.

P.S.The domain I'm trying to use is in my Route 53 account and I have tested it before that all works fine with other services.
